### ISSUE TITLE
The test/demo program for the tick generator should demonstrate an absolute tick request

### ISSUE THREAD

**Issue by pchapin** [cubesatlab/cubedos#14]
Currently the test/demo program for the tick generator demonstrates relative tick requests and tick cancellation requests. It should also demonstrate absolute tick requests. This will probably require it to display, for each event, relative time from the start of the program *and* absolute time (so the user can compare the behavior with the expected behavior).

**Comment by DevonDiianni** [comment]
Updated with absolute time stamp.
