### ISSUE TITLE
Modify Ping Pong so it measures message processing performance in some useful way

### ISSUE THREAD

**Issue by pchapin** [cubesatlab/cubedos#6]
The basic Ping Pong example application could be useful for exploring some performance issues with CubedOS. We definitely need to have a way of quantifying the message passing overhead, not only for comparisons with other systems, but also as a baseline for comparisons with future enhancements to CubedOS.

**Comment by DavidMiserak** [comment]
Is Ping Pong now the Echo Sample?

**Comment by pchapin** [comment]
Yes, it is. In fact, the Echo sample does measure message processing performance in "some useful way." What it does isn't very sophisticated, but it's a start. I think this issue can be closed. If we want something more, we can open a new one.
